version: '2'

services:
    node-server:
        container_name: server
        build:
            context: .
        volumes:
            - .:/home/blacktab
            - /home/blacktab/node_modules
        tty: true
        environment:
            - NODE_ENV=development
            - DEBUG=db*
        ports:
            - "3000:3000"
            - "5858:5858"
        depends_on:
            - mongo

    mongo:
        container_name: database
        image: mongo
        tty: true
        volumes:
            - ./data/db:/data/db
        ports:
            - "27017:27017"

networks:
    local-network:
        driver: bridge
